sudo: required
language: python
notifications:
  email:
    recipients:
      - x94carbone@gmail.com
    on_success: never
    on_failure: always
install:
  - pip install coveralls
  - pip install PyYAML
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
script:
  - coverage run --source=paragon ./test.py
after_success: coveralls
