sudo: required
language: python3
before_script: cd paragon
notifications:
  email:
    recipients:
      - x94carbone@gmail.com
    on_success: never
    on_failure: always
install:
  - pip install coveralls
python:
  - '3.5'
  - '3.6'
  - '3.7'
script:
  - coverage run --source=paragon python3 test.py
after_success: coveralls
